[package]
name = "annealing"
version = "1.0.0"
authors = ["unsharot"]
edition = "2021"
description = "A crate to provide Simulated Annealing for kinmu."

[lib]
name = "annealing"
path = "src/lib.rs"

[dependencies]
rand = "0.8.5"
