[package]
name = "kinmu"
version = "1.0.3"
authors = ["unsharot"]
edition = "2021"
description = "A project that solves specific nurse scheduling problem."
repository = "https://github.com/unsharot/kinmu_rs"

[workspace]
members = [
    "annealing",
]

[dependencies]
rand = "0.8.5"
annealing = { path = "annealing" }
