[package]
name = "kinmu"
version = "2.2.2"
authors = ["unsharot"]
edition = "2021"
description = "A project that solves specific nurse scheduling problem."
repository = "https://github.com/unsharot/kinmu_rs"

[workspace]
members = [
    "annealing",
]

[dependencies]
rand = "0.8.5"
annealing = { path = "annealing" }
serde = { version = "1.0.145", features = ["derive"] }
toml = "0.8.19"
color-print = "0.3.7"
getopts = "0.2.21"
