# 焼きなましのステップ数
step_count = 10000

# 焼きなましに用いる乱数シード値
# 指定する場合、有効化する
# seed = 0

# 焼きなましに用いるスコア関数
score_functions = [
  {display_name = "日勤", scores = ["StaffCount (NoBuffer (), N, 2, 100)"], filter = {low_pass = 1000}},
  {display_name = "夜勤人数", scores = ["StaffCountRegardDayAttribute (NoBuffer (), I, 夜勤, 1000)"], filter = {low_pass = 1000}},
  {display_name = "夜勤制約", scores = [
    "PatternGeneral (True (), [[I], [N,O,H,I,K,Y]], 100000)",
    "PatternGeneral (True (), [[A], [N,O,H,I,A]], 100000)",
    "PatternGeneral (True (), [[N,O,H,A,K,Y], [A]], 100000)"
  ], filter = {low_pass = 10000}}
]

# 更新に用いる関数
update_function = "update1"

# 焼きなましの温度を指定
temp = {max = 10000, min = 0}
