step_count = 200000

# seed = 0

score_functions = [

{display_name = "ON", scores = [
"PatternFixed (True (), [O,N], 100)",
]},

{display_name = "NH", scores = [
"PatternFixed (True (), [N,H], 1000)",
]},

{display_name = "OH", scores = [
"PatternFixed (True (), [O,H], 2000)",
]},

{display_name = "遅早のバランス", scores = [
"ShiftsBalance (NoBuffer (), O, H, 3)",
]},

{display_name = "遅番の前後のバランス", scores = [
"ShiftHalfBalance (NoBuffer (), O, 3)",
]},

{display_name = "早番の前後のバランス", scores = [
"ShiftHalfBalance (NoBuffer (), H, 3)",
]},

{display_name = "フロのスタッフ数", scores = [
"StaffCount (And (NoBuffer (), DayState B), N, 3, 5)",
]},

{display_name = "フロ2のスタッフ数", scores = [
"StaffCount (And (NoBuffer (), DayState 2), N, 1, 10)",
]},

{display_name = "平日のスタッフ数", scores = [
"StaffCount (And (NoBuffer (), DayState W), N, 1, 10)",
]},

{display_name = "休日のスタッフ数", scores = [
"StaffCount (And (NoBuffer (), DayState H), N, 1, 10)",
]},

{display_name = "計測のスタッフ数", scores = [
"StaffCount (And (NoBuffer (), DayState M), N, 1, 10)",
]},

{display_name = "遅番のスタッフ数", scores = [
"StaffCount (NoBuffer (), O, 1, 100)",
],warning={min_pass=0}},

{display_name = "早番のスタッフ数", scores = [
"StaffCount (NoBuffer (), H, 1, 100)",
],warning={min_pass=0}},

{display_name = "遅番の日数", scores = [
"DayCountRegardStaffAttribute (And (Not StaffWithAttribute (ODayCount, -1), NoBuffer ()), O, ODayCount, 100)",
],warning={min_pass=0}},

{display_name = "早番の日数", scores = [
"DayCountRegardStaffAttribute (And (Not StaffWithAttribute (HDayCount, -1), NoBuffer ()), H, HDayCount, 100)",
],warning={min_pass=0}},

]

update_function = "update_noh_repeat"

temperature = {begin = 10000, end = 0}
