[package]
name = "kinmu_color"
version = "0.1.0"
authors = ["unsharot"]
edition = "2021"
license = "MIT"
description = "Provides color print for kinmu."
repository = "https://github.com/unsharot/kinmu_rs"

[dependencies]
color-print = "0.3.7"
