[package]
name = "kinmu_output"
version = "0.1.0"
edition = "2021"

[dependencies]
kinmu_lib = { workspace = true }
kinmu_color = { workspace = true }
kinmu_core = { workspace = true }
anyhow = { workspace = true }
