[package]
name = "kinmu_annealing"
version = "0.1.0"
authors = ["unsharot"]
edition = "2021"
description = "A crate to provide Simulated Annealing for kinmu."

[dependencies]
rand = { workspace = true }
